---
name: Browserweb
version: 1.1
slug: puppeteer
description: An addon that builds a browser for use in the webui.
url: https://github.com/Subzerox64/hassio-addons
startup: application
arch:
  - amd64
  - armv7
  - arm64
webui: true
options:
  rfbproxy_port: 5900
schema:
  rfbproxy_port: int
  
